config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'dashboard#index', as: :dashboard
    resources :users, only: [:index, :new, :create, :show, :destroy]
    resources :notifications, only: [:index, :show]
    resources :job_offers, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :applies, only: [:index, :show]
    end
    get 'last_applies', to: 'applies#index', as: :last_applies
  end
  

  namespace :regular_users do
    resources :dashboard, only: [:index]
    resources :users, only: [:show]
    resources :job_offers, only: [:index, :show] do
      resources :applies, only: [:index, :show, :create]
    end
    get 'applies', to: 'applies#index', as: :applies
  end
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }

  root 'home#index'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
  has_many :applies, dependent: :destroy

  validates :title, :description, :requirements, presence: true

  def applied_by?(user)
    applies.exists?(user: user)
  end

  def applied_date(user)
    apply = applies.find_by(user: user)
    apply.created_at.strftime('%d/%m/%Y')
  end
  
  
end

app/controllers/admin/job_offers_controller.rb
class Admin::JobOffersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

    def index
        @job_offers = JobOffer.all

        @pagy, @job_offers = pagy(JobOffer.all) # Gema pagy
    end

    def new
        @job_offer = JobOffer.new
    end
    
    def create
        @job_offer = current_user.job_offers.new(job_offer_params)
    
        if @job_offer.save
            redirect_to admin_job_offers_path, notice: 'Oferta creada con éxito'
        else
            render :new
        end
    end
    
    def show
    end

    def edit
    end

    def update
        if @job_offer.update(job_offer_params)
            redirect_to admin_job_offer_path(@job_offer), notice: 'Job offer was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @job_offer.destroy
        redirect_to admin_job_offers_path, notice: 'Job offer was successfully destroyed.'
    end

    private

    def set_job_offer
        @job_offer = JobOffer.find(params[:id])
    end
    
    def job_offer_params
        params.require(:job_offer).permit(:title, :description, :requirements)
    end
end

app/controllers/regular_users/applies_controller.rb
class RegularUsers::AppliesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_applies

  def index
    @applied_job_offers = @applies.map(&:job_offer)
  end

  def show
    @job_offer = JobOffer.find(params[:id])
  end

  def create
    @job_offer = JobOffer.find(params[:job_offer_id])
    @apply = current_user.applies.build(job_offer: @job_offer)

    if @apply.save
      create_notification(@apply.user, @apply.job_offer)
      redirect_to regular_users_job_offer_path(@job_offer), notice: 'Has sido postulado exitosamente'
    else
      redirect_to regular_users_job_offer_path(@job_offer), alert: 'Ya te has postulado a esta oferta'
    end
  end

  private

  def set_user_applies
    @applies = current_user.applies
  end

  def create_notification(user, job_offer)
    Notification.create(user: job_offer.user, job_offer: job_offer, content: "#{user.full_name} ha postulado a #{job_offer.title}")
  end
end

app/controllers/regular_users/dashboard_controller.rb
class RegularUsers::DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
    end
end

app/controllers/regular_users/job_offers_controller.rb
class RegularUsers::JobOffersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_job_offer, only: [:show]

    def index
        @job_offers = JobOffer.all
    end
    
    def show
        @applies = @job_offer.applies
        @new_apply = Apply.new # Para el formulario de nueva postulación
    end

    private

    def set_job_offer
        @job_offer = JobOffer.find(params[:id])
    end
end

app/controllers/regular_users/users_controller.rb
class RegularUsers::UsersController < ApplicationController
    before_action :set_user, only: [:show]

    def show
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/admin/job_offers_helper.rb
module Admin::JobOffersHelper
end

app/helpers/regular_users/applies_helper.rb
module RegularUsers::AppliesHelper
end

app/helpers/regular_users/job_offers_helper.rb
module RegularUsers::JobOffersHelper
end

app/helpers/regular_users/profiles_helper.rb
module RegularUsers::ProfilesHelper
end

app/helpers/regular_users/users_helper.rb
module RegularUsers::UsersHelper
end

app/views/regular_users/job_offers/index.html.erb
<div class="regular-user-container">
    <h1 class="regular-user-title">Ofertas Laborales</h1>

    <ul class="regular-user-job-offers">
        <% @job_offers.each do |job_offer| %>
            <li class="regular-user-job-offer-item">
                <div class="regular-user-job-offer-info">
                    <%= link_to job_offer.title, regular_users_job_offer_path(job_offer), class: "regular-user-job-offer-title" %>
                </div>
                <div class="regular-user-job-offer-actions">
                    <%= link_to 'Ver detalle', regular_users_job_offer_path(job_offer), class: 'regular-user-job-offer-button' %>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/regular_users/job_offers/show.html.erb
<div class="job-offer-show-container">
    <h1 class="job-offer-title"><%= @job_offer.title %></h1>
    <p class="job-offer-description"><strong>Descripción:</strong> <%= @job_offer.description %></p>
    <p class="job-offer-requirements"><strong>Requerimientos:</strong><%= @job_offer.requirements %></p>
    <hr>

    <% if @job_offer.applied_by?(current_user) %>
        <p class="job-offer-applied">Aplicaste a esta oferta el día <%= @job_offer.applied_date(current_user) %></p>
    <% else %>
        <h2 class="job-offer-apply-title">Realizar Postulación</h2>
        <%= form_with(model: @apply, url: regular_users_job_offer_applies_path(@job_offer), method: :post, class: 'apply-form') do |f| %>
            <%= f.hidden_field :job_offer_id %>
            <%= f.submit 'Postular', class: 'btn btn-primary apply-button' %>
        <% end %>
    <% end %>
</div>
<div class="edit-job-offer-back">
    <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver a las ofertas'), regular_users_job_offers_path, class: "admin-btn edit-job-offer-back-btn" %>
</div>