config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'dashboard#index', as: :dashboard
    resources :users, only: [:index, :new, :create, :show, :destroy]
    resources :notifications, only: [:index, :show]
    resources :job_offers, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :applies, only: [:index, :show]
    end
    get 'last_applies', to: 'applies#index', as: :last_applies
  end
  

  namespace :regular_users do
    resources :dashboard, only: [:index]
    resources :users, only: [:show]
    resources :job_offers, only: [:index, :show] do
      resources :applies, only: [:index, :show, :create]
    end
    get 'applies', to: 'applies#index', as: :applies
  end
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }

  root 'home#index'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
  has_many :applies, dependent: :destroy

  validates :title, :description, :requirements, presence: true

  def applied_by?(user)
    applies.exists?(user: user)
  end

  def applied_date(user)
    apply = applies.find_by(user: user)
    apply.created_at.strftime('%d/%m/%Y')
  end
  
  
end

app/controllers/admin/job_offers_controller.rb
class Admin::JobOffersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

    def index
        @job_offers = JobOffer.all

        @pagy, @job_offers = pagy(JobOffer.all) # Gema pagy
    end

    def new
        @job_offer = JobOffer.new
    end
    
    def create
        @job_offer = current_user.job_offers.new(job_offer_params)
    
        if @job_offer.save
            redirect_to admin_job_offers_path, notice: 'Oferta creada con éxito'
        else
            render :new
        end
    end
    
    def show
    end

    def edit
    end

    def update
        if @job_offer.update(job_offer_params)
            redirect_to admin_job_offer_path(@job_offer), notice: 'Job offer was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @job_offer.destroy
        redirect_to admin_job_offers_path, notice: 'Job offer was successfully destroyed.'
    end

    private

    def set_job_offer
        @job_offer = JobOffer.find(params[:id])
    end
    
    def job_offer_params
        params.require(:job_offer).permit(:title, :description, :requirements)
    end
end

app/controllers/regular_users/job_offers_controller.rb
class RegularUsers::JobOffersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_job_offer, only: [:show]

    def index
        @job_offers = JobOffer.all
    end
    
    def show
        @applies = @job_offer.applies
        @new_apply = Apply.new # Para el formulario de nueva postulación
    end

    private

    def set_job_offer
        @job_offer = JobOffer.find(params[:id])
    end
end

app/helpers/admin/job_offers_helper.rb
module Admin::JobOffersHelper
end

app/helpers/regular_users/job_offers_helper.rb
module RegularUsers::JobOffersHelper
end

app/views/admin/job_offers/_form.html.erb
<%= form_with(model: @job_offer, url: admin_job_offers_path) do |f| %>
    <div>
        <%= f.label :title, "Título" %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div>
        <%= f.label :description, "Descripción" %>
        <%= f.text_area :description, class: "form-control" %>
    </div>

    <div>
        <%= f.label :requirements, "Requerimientos" %>
        <%= f.text_area :requirements, class: "form-control" %>
    </div>

    <div>
        <%= f.submit 'Crear', class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/job_offers/_job_offer.html.erb
<div class="job-offer">
    <h2><%= job_offer.title %></h2>
    <p><%= job_offer.description %></p>
    <p><%= job_offer.requirements %></p>
</div>

app/views/admin/job_offers/edit.html.erb
<div class="edit-job-offer-container">
    <h1 class="edit-job-offer-title">Editar Oferta Laboral</h1>
    <%= form_with(model: @job_offer, url: admin_job_offer_path(@job_offer), method: :patch) do |f| %>
        <div class="form-group">
            <%= f.label :title, "Título" %>
            <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :description, "Descripción" %>
            <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :requirements, "Requerimientos" %>
            <%= f.text_area :requirements, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.submit 'Actualizar', class: "btn btn-primary mt-2 edit-job-offer-submit" %>
        </div>
    <% end %>
</div>

<div class="edit-job-offer-back">
    <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver'), :back, class: "admin-btn edit-job-offer-back-btn" %>
</div>

app/views/admin/job_offers/index.html.erb
<h1 class="admin-heading">Ofertas Laborales</h1>

<%= link_to 'Crear nueva Oferta', new_admin_job_offer_path, class: 'admin-btn my-4' %>
<%== pagy_bootstrap_nav(@pagy) %> <!--gema pagy-->
<table class="admin-table">
    <thead>
        <tr>
            <th>Fecha publicación</th>
            <th>Título</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <% @job_offers.each do |job_offer| %>
        <tr>
            <td><%= job_offer.created_at.strftime('%d/%m/%Y') %></td>
            <td><%= job_offer.title %></td>
            <td><%= job_offer.requirements %></td>
            <td>
            <div class="btn-group">
                <%= link_to 'Ver', admin_job_offer_path(job_offer), class: 'admin-action-btn' %>
                <%= link_to 'Editar', edit_admin_job_offer_path(job_offer), class: 'admin-action-btn' %>
            </div>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/job_offers/new.html.erb
<h1>Nueva Oferta Laboral</h1>
<%= form_with(model: @job_offer, url: admin_job_offers_path) do |f| %>
    <div>
        <%= f.label :title, "Título" %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div>
        <%= f.label :description, "Descripción" %>
        <%= f.text_area :description, class: "form-control" %>
    </div>

    <div>
        <%= f.label :requirements, "Requerimientos" %>
        <%= f.text_area :requirements, class: "form-control" %>
    </div>

    <div>
        <%= f.submit 'Crear', class: "btn btn-primary" %>
    </div>
<% end %>


<div class="edit-job-offer-back">
    <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver'), admin_job_offers_path, class: "admin-btn edit-job-offer-back-btn" %>
</div>

app/views/admin/job_offers/show.html.erb
<div class="job-offer-card">
    <h1 class="job-offer-title"><%= @job_offer.title %></h1>
    <hr>

    <div class="job-offer-info">
        <p><strong>Descripción:</strong></p>
        <p class="job-offer-description"><%= @job_offer.description %></p>

        <p><strong>Requerimientos:</strong></p>
        <p class="job-offer-requirements"><%= @job_offer.requirements %></p>
    </div>


    <div class="job-offer-actions">
        <%= link_to 'Editar', edit_admin_job_offer_path(@job_offer), class: 'edit-btn' %>
        <%= button_to 'Eliminar', admin_job_offer_path(@job_offer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-btn2' %>
    </div>
</div>

<div class="edit-job-offer-back">
    <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver'), admin_job_offers_path, class: "admin-btn edit-job-offer-back-btn" %>
</div>