config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'dashboard#index', as: :dashboard
    resources :users, only: [:index, :new, :create, :show, :destroy]
    resources :notifications, only: [:index, :show]
    resources :job_offers, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :applies, only: [:index, :show]
    end
    get 'last_applies', to: 'applies#index', as: :last_applies
  end
  

  namespace :regular_users do
    resources :dashboard, only: [:index]
    resources :users, only: [:show]
    resources :job_offers, only: [:index, :show] do
      resources :applies, only: [:index, :show, :create]
    end
    get 'applies', to: 'applies#index', as: :applies
  end
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  belongs_to :job_offer


  validates :user_id, uniqueness: { scope: :job_offer_id, message: 'Ya te has postulado a esta oferta.' }
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
  has_many :applies, dependent: :destroy

  validates :title, :description, :requirements, presence: true

  def applied_by?(user)
    applies.exists?(user: user)
  end

  def applied_date(user)
    apply = applies.find_by(user: user)
    apply.created_at.strftime('%d/%m/%Y')
  end
  
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :job_offer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        enum role: { regular: 0, admin: 1 }

        has_one_attached :avatar, dependent: :destroy
        has_many :applies, dependent: :destroy
        # Asociación para las ofertas laborales creadas por el admin
        has_many :job_offers, class_name: 'JobOffer'

        # Validaciones para los campos adicionales
        validates :first_name, :last_name, :position, :department, :bio, presence: true
        validates :email, uniqueness: true
        
        include PgSearch::Model

        pg_search_scope :search_by_name, against: [:first_name, :last_name]

        def default_avatar_url
          ActionController::Base.helpers.asset_path("default_avatar.jpg")
        end

        def full_name
          "#{first_name} #{last_name}"
        end

        def unread_applies_notifications_count
          applies = self.applies.joins(:job_offer)
          Notification.where(job_offer_id: applies.pluck(:job_offer_id), read: false).count
        end
end

app/controllers/admin/applies_controller.rb
class Admin::AppliesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @job_offers_with_applies = JobOffer.joins(:applies).distinct

    @pagy, @job_offers_with_applies = pagy(JobOffer.joins(:applies).distinct)
    
  end

  def show
    @job_offer = JobOffer.find(params[:job_offer_id])
    @applicants = @job_offer.applies.map(&:user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!

    def index
        if params[:query].present?
            search_query = "%#{params[:query]}%" # Agregar % al principio y al final para búsqueda parcial
    
            @users = User.where(role: 'regular')
                        .where("first_name ILIKE ? OR last_name ILIKE ?", search_query, search_query)
                        .order(created_at: :desc)
        else
            @users = User.where(role: 'regular').order(created_at: :desc)
        end

        @pagy, @users = pagy(@users) # Gema pagy
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.password = "password2023"
        @user.password_confirmation = "password2023"
    
        if @user.save
            redirect_to admin_dashboard_path, notice: 'Usuario creado con éxito'
        else
            flash.now[:alert] = 'Hubo un problema al crear el usuario'
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path, notice: 'Usuario eliminado con éxito.'
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :position, :department, :bio, :role)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pagy::Backend
    require 'pagy/extras/bootstrap'
    Pagy::DEFAULT[:items] = 9        # items per page


    def authenticate_admin!
        unless current_user&.admin?
            redirect_to root_path, alert: 'Access denied.'
        end
    end

    def after_sign_in_path_for(resource)
        if resource.admin?
            admin_dashboard_index_path
        else
            regular_users_dashboard_index_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/applies_helper.rb
module Admin::AppliesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/job_offers_helper.rb
module Admin::JobOffersHelper
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regular_users/applies_helper.rb
module RegularUsers::AppliesHelper
end

app/helpers/regular_users/users_helper.rb
module RegularUsers::UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg py-3">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto ps-5 pt-2">
                <% if current_user.admin? %>
                <li class="nav-item">
                    <%= link_to "Inicio", admin_dashboard_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Ofertas Laborales", admin_job_offers_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Postulaciones", admin_last_applies_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Usuarios", admin_users_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= admin_notifications_path %>">
                        <i id="notification-icon" class="far fa-envelope"></i>
                        <i class=""></i>
                    </a>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Inicio", regular_users_dashboard_index_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Ofertas Laborales", regular_users_job_offers_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Mis Postulaciones", regular_users_applies_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Perfil", regular_users_user_path(current_user), class: "nav-link" %>
                </li>
                <% end %>
            </ul>
            <ul class="navbar-nav ms-auto pe-4">
                <li class="nav-item">
                    <span class="nav-link">Hola, <%= current_user.first_name %></span>
                </li>
                <li class="nav-item">
                    <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "btn btn-link nav-link" %>
                </li>
            </ul>
        </div>
    </nav>
<% end %>