config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'dashboard#index', as: :dashboard
    resources :users, only: [:index, :new, :create, :show, :destroy]
    resources :notifications, only: [:index, :show]
    resources :job_offers, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :applies, only: [:index, :show]
    end
    get 'last_applies', to: 'applies#index', as: :last_applies
  end
  

  namespace :regular_users do
    resources :dashboard, only: [:index]
    resources :users, only: [:show]
    resources :job_offers, only: [:index, :show] do
      resources :applies, only: [:index, :show, :create]
    end
    get 'applies', to: 'applies#index', as: :applies
  end
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        enum role: { regular: 0, admin: 1 }

        has_one_attached :avatar, dependent: :destroy
        has_many :applies, dependent: :destroy
        # Asociación para las ofertas laborales creadas por el admin
        has_many :job_offers, class_name: 'JobOffer'

        # Validaciones para los campos adicionales
        validates :first_name, :last_name, :position, :department, :bio, presence: true
        validates :email, uniqueness: true
        
        include PgSearch::Model

        pg_search_scope :search_by_name, against: [:first_name, :last_name]

        def default_avatar_url
          ActionController::Base.helpers.asset_path("default_avatar.jpg")
        end

        def full_name
          "#{first_name} #{last_name}"
        end

        def unread_applies_notifications_count
          applies = self.applies.joins(:job_offer)
          Notification.where(job_offer_id: applies.pluck(:job_offer_id), read: false).count
        end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!

    def index
        if params[:query].present?
            search_query = "%#{params[:query]}%" # Agregar % al principio y al final para búsqueda parcial
    
            @users = User.where(role: 'regular')
                        .where("first_name ILIKE ? OR last_name ILIKE ?", search_query, search_query)
                        .order(created_at: :desc)
        else
            @users = User.where(role: 'regular').order(created_at: :desc)
        end

        @pagy, @users = pagy(@users) # Gema pagy
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.password = "password2023"
        @user.password_confirmation = "password2023"
    
        if @user.save
            redirect_to admin_dashboard_path, notice: 'Usuario creado con éxito'
        else
            flash.now[:alert] = 'Hubo un problema al crear el usuario'
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path, notice: 'Usuario eliminado con éxito.'
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :position, :department, :bio, :role)
    end
end

app/controllers/regular_users/users_controller.rb
class RegularUsers::UsersController < ApplicationController
    before_action :set_user, only: [:show]

    def show
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # POST /resource
  def create
    if params[:user][:role] == 'regular'
      super
    else
      redirect_to root_path, alert: 'Only admin users can register new regular users.'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super do |resource|
      redirect_to regular_users_user_path(resource) and return if resource.valid?
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :position, :department, :bio, :role, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :position, :department, :bio, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_dashboard_path
    else
      regular_users_dashboard_index_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/regular_users/users_helper.rb
module RegularUsers::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="admin-container">
    <h1 class="admin-header">Empleados Registrados</h1>

    <%= link_to "Crear Nuevo Usuario", new_admin_user_path, class: "admin-btn" %>

    <!-- Formulario de Búsqueda -->
    <%= form_with(url: admin_users_path, method: "get", class: "search-form") do |f| %>
    <div class="input-group rounded my-3">
        <%= f.text_field :query, class: "form-control rounded-start", placeholder: "Ejemplo: Juan Pérez" %>
        <button type="submit" class="btn btn-primary rounded-end">
        <i class="fas fa-search"></i> <!-- Icono de lupa -->
        </button>
    </div>
    <% end %>
    <!--Fin Formulario de Búsqueda -->

    <%== pagy_bootstrap_nav(@pagy) %> <!-- Gema pagy -->

    <div class="users-list">
        <% @users.each do |user| %>
        <div class="admin-card">
            <div class="user-avatar">
            <% if user.avatar.attached? %>
                <%= image_tag user.avatar, class: "user-avatar-img" %>
            <% else %>
                <%= image_tag 'default_avatar.jpg', class: "user-avatar-img" %>
            <% end %>
            </div>
            <div class="user-details">
            <p><strong>Fecha de Creación:</strong> <%= user.created_at.strftime('%d/%m/%Y %H:%M:%S') %></p>
            <p class="user-name"><strong>Nombre:</strong> <%= user.first_name %> <%= user.last_name %></p>
            <p><strong>Correo Electrónico:</strong> <%= user.email %></p>
            </div>
            <div class="user-actions">
            <%= link_to "Ver Detalle", admin_user_path(user), class: "view-btn" %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/admin/users/new.html.erb
<div class="user-form mb-4">
  <h2 class="py-2">Nuevo Usuario</h2>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @user, url: admin_users_path do |f| %>
    <div class="form-group">
      <%= f.label :Nombre, class: "form-label" %>
      <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Apellido, class: "form-label" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "form-label" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Cargo, class: "form-label" %>
      <%= f.text_field :position, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Departamento, class: "form-label" %>
      <%= f.text_field :department, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Presentación, class: "form-label" %>
      <%= f.text_area :bio, rows: 4, value: 'Debe completar el empleado', class: 'form-control default-bio' %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, "Foto de Perfil", class: "form-label" %>
      <%= f.file_field :avatar, value: @user.default_avatar_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :role, class: "form-label" %>
      <%= f.select :role, User.roles.keys, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Contraseña_Predefinida, class: "form-label" %>
      <div class="password-field">
        <%= f.password_field :password, class: 'form-control default-password' %>
      </div>
    </div>

    <%= f.submit "Crear Usuario", class: "btn btn-primary mb-2" %>
  <% end %>

  <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver'), :back, class: "admin-btn" %>
</div>

app/views/admin/users/show.html.erb
<div class="admin-card-show">
    <div class="admin-card-header">
        Detalle del Empleado
    </div>
    <div class="admin-card-body">
        <div class="user-details">
            <p><strong>Nombre:</strong> <%= @user.first_name %> <%= @user.last_name %></p>
            <p><strong>Correo Electrónico:</strong> <%= @user.email %></p>
            <p><strong>Cargo:</strong> <%= @user.position %></p>
            <p><strong>Departamento:</strong> <%= @user.department %></p>
        </div>
        <div class="user-avatar">
            <% if @user.avatar.attached? %>
                <%= image_tag @user.avatar, class: 'profile-avatar' %>
            <% else %>
                <%= image_tag 'default_avatar.jpg', class: 'profile-avatar' %>
            <% end %>
        </div>
    </div>
    <div class="user-bio">
        <p><strong>Biografía:</strong></p>
        <p><%= @user.bio %></p>
    </div>
    <div class="user-actions">
        <%= button_to "Eliminar Usuario", admin_user_path(@user), method: :delete, data: { confirm: "¿Estás seguro de que deseas eliminar este usuario?" }, class: "delete-btn2 ms-2 my-4" %>
    </div>
</div>

<div class="edit-job-offer-back">
    <%= link_to raw('<i class="fas fa-arrow-left"></i> Volver'), :back, class: "admin-btn edit-job-offer-back-btn" %>
</div>